/**:
  ros__parameters:
    # construction parameters
    preprocessor:
      name: "YOLO"
    engine:
      name: "openvino"
      # absolute path to the .xml. Openvino will search for the .bin in the same directory
      model_path: "/home/vscode/ws/src/rm_detector2026/models/yolov10-pose/yolov10_openvino.xml"
    decoder:
      name: "yolov10_decoder"
      conf_threshold: 0.1
    postprocessor:
      IsUsed: true
      p1:
        name: "nms"
        iou_threshold: 0.1
      # p2:
      #   name: "rule_based_filter"
